spring.application.name=Txnora

spring.data.mongodb.uri=mongodb://localhost:27017/txnora

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=txnora-workflow-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# TEMP DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka.clients.consumer=INFO